const data = [
  {
    url: "https://unsplash.com/photos/j-8ZmtO-8DQ",
    name: "Woo Ninja",
    color: "Pink",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "L",
  },
  {
    url: "https://unsplash.com/photos/lEUAwTHGmzY",
    name: "Woo Logo",
    color: "Blue",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "XL",
  },
  {
    url: "https://unsplash.com/photos/lEUAwTHGmzY",
    name: "Patient Ninja",
    color: "Black",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "M",
  },
  {
    url: "https://unsplash.com/photos/ZXVeKAKtwvY",
    name: "Pro Ninja",
    color: "Black",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "L",
  },
  {
    url: "https://unsplash.com/photos/9fbYYM677_A",
    name: "Illusion Tshirt ",
    color: "Red",
    Stock: true,
    price: 21.0,
    type: "tshirt",
    size: "XL",
  },
  {
    url: "https://unsplash.com/photos/lrAmF1IPGSI",
    name: "Logo Tshirt",
    color: "Blue",
    Stock: true,
    price: 25.0,
    type: "tshirt",
    size: "XL",
  },
  {
    url: "https://unsplash.com/photos/20oegq2JDYU",
    name: "Slim Fit Shirt",
    color: "White",
    Stock: true,
    price: 50.0,
    type: "shirt",
    size: "L",
  },
  {
    url: "https://unsplash.com/photos/af91UeNTbzQ",
    name: "Slim Fit Shirt",
    color: "Black",
    Stock: true,
    price: 50.0,
    type: "shirt",
    size: "M",
  },
];

export default data;
