const data = [
  {
    url: "",
    name: "Woo Ninja",
    color: "Pink",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "L",
  },
  {
    url: "",
    name: "Woo Logo",
    color: "Blue",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "XL",
  },
  {
    url: "",
    name: "Patient Ninja",
    color: "Pink",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "M",
  },
  {
    url: "",
    name: "Pro Ninja",
    color: "Black",
    Stock: true,
    price: 35.0,
    type: "hoodie",
    size: "L",
  },
  {
    url: "",
    name: "Illusion Tshirt ",
    color: "Red",
    Stock: true,
    price: 21.0,
    type: "tshirt",
    size: "XL",
  },
  {
    url: "",
    name: "Logo Tshirt",
    color: "Blue",
    Stock: true,
    price: 25.0,
    type: "tshirt",
    size: "XL",
  },
  {
    url: "",
    name: "Slim Fit Shirt",
    color: "White",
    Stock: true,
    price: 50.0,
    type: "shirt",
    size: "L",
  },
  {
    url: "",
    name: "Slim Fit Shirt",
    color: "Black",
    Stock: true,
    price: 50.0,
    type: "shirt",
    size: "M",
  },
];

export default data;
